### ISSUE TITLE
About evaluation metrics

### ISSUE THREAD

**Issue by 1774537072** [prs-eth/Diffusion-Super-Resolution#1]
Thank you very much for your sharing. As I am new to this field, I am not quite clear about how metrics are calculated. I would like to ask whether the evaluation metrics are obtained by run_eval.py or tested by matlab using generated graphs?

**Comment by nandometzger** [comment]
Hi, we are using the standard MAE and MSE. The metrics generated in the paper are calculated by run_eval.py and specifically in this file: https://github.com/prs-eth/Diffusion-Super-Resolution/blob/main/losses.py

Best
Nando
