### ISSUE TITLE
Question about Code

### ISSUE THREAD

**Issue by wangweiran0922** [prs-eth/Diffusion-Super-Resolution#11]
Hi, thank you for making your work open source.
I would like to ask if the segmentation_models_pytorch in gad_base.py is provided? 
Secondly I would like to ask what is the meaning of mask_lr and mask_hr in sample?
Looking forward to hearing back from you.

**Comment by nandometzger** [comment]
Hi, just install the requirements file as descibed in the readme

```
conda env create -f environment.yml
conda activate DADA-SR
```

And the pytorch segemntation models will get installed as a package.

The masks come from the fact, that the Middleburry dataset is photogrammetric. Therefore produces invalid pixels in the ground truth and subsequently also in the low resolution source. If your samples have full coverage of depth estimations, you don't have to worry about it.

**Comment by wangweiran0922** [comment]
Thank you very much for receiving your reply
