### ISSUE TITLE
Visualize results

### ISSUE THREAD

**Issue by hvelesaca** [prs-eth/Diffusion-Super-Resolution#2]
How to visualize the results obtained in the testing stage?

**Comment by nandometzger** [comment]
Thanks for the message.
We did not include the visualization code in the repository. You can replicate the plots of the paper by using matplotlib. For the depth maps, we used the "Spectral" colormap and for the residual plots, we used "RdBu" (if I remember correctly). Make sure that for the residual plots, your vmax and vmin is centered around 0.

Please let me know if there is any other question.

**Comment by caijianghe** [comment]
Hello,dear author, I have some questions about visualization. for the residual plots, how can I ensure that vmax and vmin are centered around 0? 
the following is my code, but the visualization results do not quite match what is shown in your paper.

vvmin = -np.max(np.abs(residual))
vvmax = np.max(np.abs(residual))
plt.imsave(os.path.join(root_residual, f'{idx}_{dxi}.png'), residual, cmap='RdBu', vmin=vvmin, vmax= vvmax)
