### ISSUE TITLE
Question about the evaluation metrics

### ISSUE THREAD

**Issue by pkqbajng** [prs-eth/Diffusion-Super-Resolution#3]
Hi, thanks for your excellent job. In your implementation, I found that you compute the metrics using the images which has been normalized. I'm doubt about wether this manner can influence the result or not as the other methods usually don't process images as this.

**Comment by pkqbajng** [comment]
Sorry, I found that you multiply the std while evaluating, my question has been solved.

**Comment by nandometzger** [comment]
Hi,

Thanks for your interest. Exactly, we unnormalize with the standard deviation and convert it to cm and cm^2 respectively.

Please let me know if there is anything else that you want to know.

Best
Nando
