### ISSUE TITLE
Reconstruct predictions results 

### ISSUE THREAD

**Issue by hvelesaca** [prs-eth/Diffusion-Super-Resolution#4]
I have checked the network prediction results but the output shows the split source image.

How can I do to reconstruct the result in a single image.

The images of the test set
![image](https://user-images.githubusercontent.com/51929556/233735567-a2ecbc9d-c7b1-409a-bf0a-b8bb035f18b7.png)

The code execute for this images. This show that for the 5 images 
![Captura22](https://user-images.githubusercontent.com/51929556/233735320-eb35c20b-cc67-4956-abbc-bee91ed76a2b.PNG)

**Comment by nandometzger** [comment]
Hi

Our repository does not explicitly contain the code for full-image inference.
However, you can modify the dataloader to load full images, or you can adjust the crop-size parameter of the loader.

Hope this helps.

Best
Nando
