### ISSUE TITLE
Application of Pan-Sharpening

### ISSUE THREAD

**Issue by Zoulinx** [prs-eth/Diffusion-Super-Resolution#5]
Interesting work! I noticed that you are from the Photogrammetry and Remote Sensing Institute. Have you considered applying this work to the pan-sharpening of satellite images? This means using the panchromatic image as a guide to enhance the spatial resolution of the multispectral image.

**Comment by rcdaudt** [comment]
Thank you! Yes, we have considered that. It would probably work, although the priors implicit in our formulation (piecewise smoothness within connected regions) would probably not be as good for pansharpening as it is for depth images.
