### ISSUE TITLE
python train.py error

### ISSUE THREAD

**Issue by durbar2003** [prs-eth/Diffusion-Super-Resolution#8]
I tried training using your statement, but I keep on encountering the same error:

![Screenshot from 2023-07-13 13-40-05](https://github.com/prs-eth/Diffusion-Super-Resolution/assets/74106901/35d4501d-f807-4f30-91c4-ea56e64ca2dc)

**Comment by nandometzger** [comment]
Hi,
thanks for raising this issue. There was indeed a small bug in our dataloader. I fixed it in the last two commits. Can you try again and let me know if it worked now?
 
 Best
 Nando

**Comment by durbar2003** [comment]
Yes, that fixes the issue. Thanks a bunch!
