### ISSUE TITLE
test on my own dataset

### ISSUE THREAD

**Issue by kk6398** [prs-eth/Diffusion-Super-Resolution#9]
I tried testing on my own dataset. I collected my own RGB images with the same resolution and their corresponding depth images. Then use 'scripts/create_diml_npy. py' to generate the. npy file. Then Python run_ eval. py to test and try using the plt. imsave() that you mentioned to visualize the results.
I have two questions:
1) I am trying to test whether the process of my dataset is correct, especially when generating the dataset;
2) I found that run_ Eval. py has adopted "crop size" to crop the image size. Can I test and output the original image size?

**Comment by nandometzger** [comment]
Hi, 
I recommend you to write your own dataset function. the script that you mentioned is intended to be used for the DIML dataset. 
I didn't test the function with larger crop sizes. But in principle it should be doable with little to no modification.

**Comment by kk6398** [comment]
Thank for your assist.
       I am trying to perform super-resolution on my low resolution depth map, but after reading the paper and analysing the code, I found that when preparing the dataset, the first step is to initialize a high-resolution depth map Y0(depth map). For example, I need a depth image S [1,128,160](source)for super-resolution, but I first need to initialize Y0  [1,256,320] (depth map)and then downsample Y0. So, if there is no high-resolution depth map of [1,256,320] in my dataset, how do I initialize it? Or how do I preprocess the dataloader?
         Hope to receive your help and tips.

**Comment by rcdaudt** [comment]
The best option is to initialize it with an interpolation (e.g., bicubic) of your low resolution depth image.

**Comment by kk6398** [comment]
Thank you for your reply.
I found that in your preprocessing process for each dataset(diml\nyu_v2\middlebury), it involves normalizing the depth map with the **depth_transform**, but its range is different. May I ask if this range is the maximum and minimum value for each depth map, or for the entire dataset.
What should I do with my own dataset?

**Comment by kk6398** [comment]
> The best option is to initialize it with an interpolation (e.g., bicubic) of your low resolution depth image.

Thank you for your reply.
I found that in your preprocessing process for each dataset(diml\nyu_v2\middlebury), it involves normalizing the depth map with the depth_transform, but its vlaue is different. I found "We normalize all depth maps with their respective dataset-specific standard deviation. The Mean is not subtracted since the adjustment step assumes positive values." in the Supplementary Material of the paper. 
I try to calculate the standard deviation of every depth map, which is mismatching with the given value in the repo.
May I ask how I can get the standard deviation of my own dataset?
What should I do with my own dataset?

**Comment by nandometzger** [comment]
as you said "respective dataset-specific standard deviation". You should calculate the standard deviation for the whole dataset, not just for "every depth map". If your dataset fits in memory, then it is as simple as calling `depth.std()`, where depth contains all the samples of the dataset.

**Comment by kk6398** [comment]
Hi, 

The data preprocessing involved y_bicubic obtained by the function bicubic_with_mask(), which needed to convert “source” and “mask_lr” tensor to numpy before further processing. This function needs to be run on the cpu, which takes a lot of time. I wonder if this function can be run on the gpu, which can save a lot of time.

**Comment by kk6398** [comment]
Hi,

The data preprocessing involved y_bicubic obtained by the function bicubic_with_mask(), which needed to convert “source” and “mask_lr” tensor to numpy before further processing. This function needs to be run on the cpu, which takes a lot of time. May I ask how this function can be improved on the gpu, which can save a lot of time.
